# Generated by Django 2.2.24 on 2023-04-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название(rus)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название(eng)')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название(jpn)')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images/pokemon', verbose_name='Картинка')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда появляется')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда исчезает')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('srength', models.IntegerField(blank=True, null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pokemon_entities', to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
